{{- if and .Values.ingress.enabled .Values.middleware.cacheControlNoStore.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: homepage-nocache
  namespace: {{ .Values.namespace }}
spec:
  headers:
    customResponseHeaders:
      Cache-Control: no-store
{{- end }}
