apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "34.x"
    helm:
      values: |
        service:
          type: LoadBalancer

        ports:
          web:
            port: 80
            exposedPort: 80
          websecure:
            port: 443
            exposedPort: 443
            tls:
              enabled: true

        ingressRoute:
          dashboard:
            enabled: false

        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
            allowExternalNameServices: true
          kubernetesIngress:
            enabled: true
            allowExternalNameServices: true

        certificatesResolvers:
          letsencrypt:
            acme:
              email: robs@robschwe.de
              storage: /data/acme.json
              httpChallenge:
                entryPoint: web

        persistence:
          enabled: true
          size: 128Mi

        globalArguments:
          - "--global.sendanonymoususage=false"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
