deployment:
  kind: DaemonSet

service:
  type: ClusterIP

ports:
  web:
    port: 8000
    exposedPort: 80
    hostPort: 80
  websecure:
    port: 8443
    exposedPort: 443
    hostPort: 443
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: robs@robschwe.de
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

persistence:
  enabled: true
  size: 128Mi

globalArguments:
  - "--global.sendanonymoususage=false"
