apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
binaryData: {}
data:
  homelab-realm.json: |
{{ .Files.Get "files/homelab-realm.json" | indent 4 }}
