{{- range .Values.proxies }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ops.fullname" . }}-oauth2
  namespace: {{ $.Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.priority: "50"
spec:
  ingressClassName: traefik-helm
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: {{ include "ops.fullname" . }}
                port:
                  number: 4180
{{- end }}
